#!/bin/bash

trap "{ kill %digitalwhanganui ; exit; }" EXIT

while true; do
    go install digitalwhanganui
    if [[ $? == 0 ]] ; then
        digitalwhanganui &
    fi
    cat DigitalWhanganui_stylesheet/style.css custom.css > public/css/style.css
    sleep 1
    inotifywait -q -e attrib *
    kill %digitalwhanganui
    wait %digitalwhanganui
done