#!/bin/bash

trap "{ kill %digitalwhanganui ; exit; }" EXIT

while true; do
    go install digitalwhanganui &
    grunt --gruntfile bootstrap/Gruntfile.js less:compileCore &
    wait %go
    GO_RESULT=$?
    wait %grunt
    GRUNT_RESULT=$?
    if [[ $GO_RESULT == 0 && $GRUNT_RESULT == 0 ]] ; then
        cp bootstrap/dist/css/bootstrap.css public/css/style.css
        digitalwhanganui &
    fi
    sleep 1
    inotifywait -r -q -e attrib --exclude *sdb* *
    kill %digitalwhanganui
    wait %digitalwhanganui
done